### ISSUE TITLE
Refactor cookbook to use files, instead of 'content' blocks for semodule building

### ISSUE THREAD

**Issue by Sauraus** [BackSlasher/chef-selinuxpolicy#15]
@BackSlasher this one is going to be a more significant change to how the module provider works. Right now it can only handle a single .te file, which is not enough in the case where you need to build a fully fledged semodule, including interfaces and file types.

For this I propose to re-factor the provider to support the usage of cookbook files that contain the actual .te/.fc/.if content, furthermore I will also move the actual compilation into it's own folder within the Chef.temp folder such as to exclude any accidents if anyone needs to create more than one module.

**Comment by BackSlasher** [comment]
1. Sounds legit. I only used the `module` resource to support my own modules, which were ridiculously simple. I have no issue with you extending the resource to support more use-cases. Could you describe the way the resource should look (A snippet describing how you'd use it)?
2.  This will be a challenge. I still want to support very simple modules, contained entirely in the recipe (maybe keep a `simple_module` or make this a `complex_module`). I guess some people will also want to use templates as file sources, but if that can't be accommodated it's OK.
3. Capital idea.

**Comment by zachsmorgan** [comment]
It seems like it would be less intrusive to add a "file" attribute, in addition to the content/name/force attributes that the module resource already exposes.

**Comment by BackSlasher** [comment]
I think so too ([that's how they do it in puppet](https://docs.puppetlabs.com/references/latest/type.html#file-attributes) btw, I prefer that), but I wonder if it's un-Chef-like

**Comment by zachsmorgan** [comment]
My gut instinct is that separate providers would more closely match the stuff from Opscode, with cookbook_file vs. file being the closest example. I hacked a helper to do what I needed right this second, but am looking forward to seeing the proposed changes :)

**Comment by BackSlasher** [comment]
Just writing in case it wasn't clear - I'm waiting to see some code - either the resource definition or a usage example

**Comment by Sauraus** [comment]
Sorry for the delay, here is the pull request: https://github.com/BackSlasher/chef-selinuxpolicy/pull/26

**Comment by BackSlasher** [comment]
Should be solved in 0.9.0
