### ISSUE TITLE
Ubuntu no longer officially supports selinux since Karmic

### ISSUE THREAD

**Issue by Sauraus** [BackSlasher/chef-selinuxpolicy#19]
Docs: https://wiki.ubuntu.com/SELinux, probably need to remove the generic 'debian' install of selinux from the recipe

**Comment by BackSlasher** [comment]
Do you use Ubuntu?
My cookbook only provides ways to manage SELinux (and optionally install management tools) - it doesn't purport to install a valid SELinux package, so I think it's fine.

**Comment by BackSlasher** [comment]
I think I just understood what you meant - you mean we should modify the installation recipe to raise an exception on Ubuntu.
I guess I agree. Thinking whether I should fail or just raise a warning

**Comment by BackSlasher** [comment]
Solved in `v0.6.5` by adding `raise`. Should anyone that actually uses Ubuntu (and my cookbook) have a different opinion (e.g. installing the packages is a good idea) we'll modify that
