### ISSUE TITLE
Helpers should be in a cookbook-specific module

### ISSUE THREAD

**Issue by chewi** [BackSlasher/chef-selinuxpolicy#22]
I think it is bad practise to define methods directly in `Chef::Provider`. You should define them in a module specific to this cookbook and then include them in the providers. It would also allow community cookbook writers to put this in their recipes.

```ruby
include SELinuxPolicy::Helpers
include_recipe 'selinux_policy::install' if use_selinux
```

They wouldn't want to include the install recipe unconditionally. If they don't include it at all, the resources will break when SELinux is enabled but the packages are missing.

**Comment by BackSlasher** [comment]
The first part I agree with - I merged this when I wasn't that familiar with Ruby, and I will seperate to a different module.
I don't think I should leave the mixins to the cookbook users - I'll play around with using `extend` at the instance level, like this:
```ruby
action :add do
  escaped_file_spec = Regexp.escape(new_resource.file_spec)
  execute "selinux-fcontext-#{new_resource.secontext}-add" do
    extend SELinuxPolicy::Helpers
    command lazy { "/usr/sbin/semanage fcontext -a -t #{new_resource.secontext} '#{new_resource.file_spec}' && #{restorecon(new_resource.file_spec)}" }
    not_if "/usr/sbin/semanage fcontext -l | grep -P '#{escaped_file_spec}\s.*\ssystem_u:object_r:#{new_resource.secontext}:s0'>/dev/null"
    only_if {use_selinux}
  end
end
```

**Comment by chewi** [comment]
That doesn't help the situation with the install recipe though. Calling `include` in your recipe isn't an unusual thing to do but I did get it slightly wrong above.

```ruby
::Chef::Recipe.send(:include, SELinuxPolicy::Helpers)
include_recipe 'selinux_policy::install' if use_selinux
```

Not quite as nice but you can see this technique [referenced here](http://dougireton.com/blog/2012/12/16/how-to-include-the-windows-cookbook-helper-methods-in-your-chef-recipe/). Using `extend` instead does work though as [explained here](https://www.chef.io/blog/2013/09/04/demystifying-common-idioms-in-chef-recipes/#comment-1043423275).

```ruby
extend SELinuxPolicy::Helpers
include_recipe 'selinux_policy::install' if use_selinux
```

**Comment by BackSlasher** [comment]
I thought you were talking about how I'm using it in my own recipe. I now think you're referring to how you're utilizing it in your own recipes.
Are you suggesting creating a recipe that does the `mixin`, so consumers can easily mixin for their own use, and avoid the mixin automatically (in case it breaks something elsewhere)?

**Comment by chewi** [comment]
I was referring to how you are using it in your providers but *also* how it could be used in recipes for other cookbooks. I'll submit a pull request later to ensure we're on the same page.

**Comment by BackSlasher** [comment]
Great :)
I'm onboard for making the cookbook cleaner. Not sure about the mixin
recipe though.
