### ISSUE TITLE
copy an selinux context

### ISSUE THREAD

**Issue by equick** [BackSlasher/chef-selinuxpolicy#38]
Hi @BackSlasher,

Is the following command to copy an selinux context something I could achieve with your cookbook?

```semanage fcontext -a -e /etc/httpd /myserverroot```

Thanks,
Ed

**Comment by BackSlasher** [comment]
Hi, I believe not.  
Even if there was resource support, can you do this idempotently?  
You'd need to compare both labels at runtime... Seems weird.  
What's the usecase? Different OSes?

**Comment by equick** [comment]
No. I can be specific in the labelling so not an issue. My use case is for labelling instances of apache which have a different server root to the default OS (Red Hat 6 in my case). It just makes like easier to copy the Red Hat contexts on /etc/httpd and /var/run/httpd, rather than spelling them out.

**Comment by BackSlasher** [comment]
Do you have a way to check it (to make it idempotent)?

**Comment by equick** [comment]
Not really, I can't think of a smart way. Let me close this one off for now :)
