### ISSUE TITLE
Dependency on yum is too strict

### ISSUE THREAD

**Issue by chewi** [BackSlasher/chef-selinuxpolicy#39]
Berkshelf has had to peg my version of selinux_poilcy back to 0.92 because depending on yum ~> 3.9.0 is too strict. Remember that yum is a very widely used cookbook. Please change this to ~> 3.9.

However, I question the need for the dependency anyway. I see that it's to run `yum::fedora_yum_compat` and that was added for Fedora but that has nothing specifically to do with this cookbook. If Chef doesn't work with dnf yet then that should be fixed and users who want to use Fedora in the meantime should just add this recipe to their own run lists. The yum cookbook even says as much in the README.

> This recipe should be 1st on a Fedora runlist.

**Comment by BackSlasher** [comment]
Hi.
I'm fine with loosening up the version constraint in the metadata.
About losing it completely - if I understand correctly, you're saying the responsibility for a working yum command should be outside the scope of the cookbook, right?
I haven't actually read the metadata for the yum cookbook. Will do so now

**Comment by chewi** [comment]
That's correct, yes.

**Comment by BackSlasher** [comment]
I see the comment you mentioned in the README, but not the reasoning behind it.
Did you happen to check the Fedora 23 kitchen without the `fedora_yum_compat`?

**Comment by chewi** [comment]
I expect it will break unless fedora_yum_compat is added to the start of the run list in .kitchen.yml. I will try it now. If you want so support Fedora under Kitchen while avoiding the yum dependency, you could add yum to the Berksfile instead.

**Comment by chewi** [comment]
It did indeed break and adding `fedora_yum_compat` to .kitchen.yml fixes it. I have filed a pull request.

**Comment by BackSlasher** [comment]
I have to think about this. I like the idea that this cookbook is "self sufficient" even on Fedora 23.
Maybe we'll modify the version constraint to `>=`. How would you feel about that?

**Comment by chewi** [comment]
`~> 3.9` would be safer and just as effective. Most other cookbooks use a similar value if they bother to constrain it at all. Either way, that would at least solve my problem.

I don't really understand the logic though. Surely no one is going to use this cookbook on its own and unless it appears very early in the run list, they would have to add `fedora_yum_compat` to their own run list anyway to prevent other cookbooks from breaking. Also when Chef does finally fix this, and it probably won't be long now, this cookbook will be installing yum on Fedora when it doesn't need to.

**Comment by BackSlasher** [comment]
Well, I don't like the idea of this cookbook depending on some "external
stuff" to work.
About needlessly requiring it, should someone care, they'll open a PR/issue
when it bothers them I hope
I'll do these stuff next week I guess (Fri/Sat are my days off).

*Nitzan Raz*
http://backslasher.net

**Comment by chewi** [comment]
Okay, thanks.

**Comment by BackSlasher** [comment]
Fixed in `v0.9.5`. Please re-open if not solved
