### ISSUE TITLE
In Chef 13 this will become an error: Option port must be a kind of [Integer]! 

### ISSUE THREAD

**Issue by equick** [BackSlasher/chef-selinuxpolicy#45]
Hi Nitz,

I've noticed the following message popping up lately with chef 12.10.24

```
Default value "10040" is invalid for property port of resource selinux_policy_port. In Chef 13 this will become an error: Option port must be a kind of [Integer]!  You passed "10040".. at 1 location:
           - /tmp/kitchen/cache/cookbooks/selinux_policy/providers/port.rb:22:in `block in class_from_file'
```

I fixed the message by updating the port attribute in selinux_policy/resources/port.rb to a String:

```
#attribute :port, :kind_of => Integer, :name_attribute => true
attribute :port, :kind_of => String, :name_attribute => true
```

Would you be happy for me to submit a PR for this or do you prefer a different fix?

Edward

**Comment by BackSlasher** [comment]
Hi
Is there a use case where port is not an integer? Also, where is this default value from?

**Comment by equick** [comment]
Yes I believe in these cases it is treated as a string:
```
$ grep execute selinux_policy/providers/port.rb
  execute "selinux-port-#{new_resource.port}-add" do
  execute "selinux-port-#{new_resource.port}-delete" do
  execute "selinux-port-#{new_resource.port}-modify" do
```

The default value refers to the port number I was setting up eg,
```
status_port = settings['modstatus']['port']
p = selinux_policy_port status_port do
  protocol 'tcp'
  secontext 'http_port_t'
end
```

where the port attribute above is defined in the attributes file as `default["httpd"][app]["modstatus"]["port"]=10040`

**Comment by BackSlasher** [comment]
Oh. Well that settles the default part.
About the string:
```
nitz@mars:~$ irb
irb(main):001:0> "a#{5}b"
=> "a5b"
```
So that's no problem. (I love ruby)
I think we should keep it an int and feed it int values (e.g. your
attribute should be `node.default['settings']['modstatus']['port'] = 5` and
not `node.default['settings']['modstatus']['port'] = "5"`).
I see that you wrote it like the attribute is an int already, is it really
so? (Check with `node.default['settings']['modstatus']['port'].class`,
should be `Fixnum`)

*Nitzan Raz*
http://backslasher.net

**Comment by equick** [comment]
Yes in my attributes I already defined it without the quotes. I have just tried this at home with a clean slate using the example in your README:
```
selinux_policy_port '5678' do
    protocol 'tcp'
    secontext 'http_port_t'
end
```
And that gives me the same error as well although obviously the port is in quotes there. So I tried it without the quotes and got exactly the same result.

**Comment by BackSlasher** [comment]
I'm a bit far away from messing with this cookbook atm. Could you please
test using a debug print in the provider whether the data passed in string
or int?

*Nitzan Raz*
http://backslasher.net

**Comment by equick** [comment]
No probs :) So testing this code:
```
selinux_policy_port 5681 do
    protocol 'tcp'
    secontext 'http_port_t'
end

```
In selinux_policy-0.9.5/providers/port.rb I added the following debug (let me know if this looks wrong):
```
action :add do
  datatype=new_resource.port.class
  Chef::Log.warn("port data type passed is #{datatype}")
  execute "selinux-port-#{new_resource.port}-add" do
```
And got this output in the chef-client run
```
Recipe: setest::default
  * selinux_policy_port[5681] action addormodify[2016-06-02T22:15:13+01:00] INFO: Processing selinux_policy_port[5681] action addormodify (setest::default line 7)
[2016-06-02T22:15:13+01:00] WARN: port data type passed is String
```

**Comment by BackSlasher** [comment]
Maybe this is the `name_attribute` thing. Try manually specifying the port
(`port 5681`)?
if so we'll have to think what to do.

*Nitzan Raz*
http://backslasher.net

**Comment by equick** [comment]
I was asking about this in the Chef channel and got the following responses:

> <coderanger> quick: The default value needs to be an int
> <coderanger> Previously we didn't check default values against the validation system.
> <coderanger> quick: It should allow both
> <coderanger> kind_of => [String, Integer]

If I update the resource to this, it removes the deprecation warning:

`attribute :port, :kind_of => [String, Integer], :name_attribute => true`

**Comment by BackSlasher** [comment]
Sure we can do that, but we agree that ports should be ints. I'll look into
why it was handed a string in the first place

*Nitzan Raz*
http://backslasher.net

**Comment by BackSlasher** [comment]
I thought about it, and the best way IMO is allow strings in the definition but have some internal logic that runs `to_i` on the value to force it to be an int. Not sure where to put it, WDYT?

**Comment by equick** [comment]
Hmm it's a tricky one. On one hand it seems like a simple fix just to add String to the kind_of section and be finished with this (it's a trivial issue after all). However I do get that the port is an Integer. I'm also not sure the deprecation error makes sense in this case, given that we are passing an integer. Do you think this is a chef issue?

**Comment by BackSlasher** [comment]
1. The resource `title` attribute type is string
2. If we put an int there, it gets converted
3. Using `name_attribute` means that `port` gets its value from the `title`
4. This means it gets a `string` value.

I was busy writing a much longer solution here, but I think I had an idea. Make it `string` and add a regex validation to ensure it looks like a number (`/\d+/`). Looks good? Are you up for it?

**Comment by equick** [comment]
Thanks you summed it up really well :) I think that sounds like an excellent solution and yes I'll give it a shot.

**Comment by equick** [comment]
Hi, is this what you had in mind?

**Comment by BackSlasher** [comment]
No, even simpler:
```
 -attribute :port, :kind_of => Integer, :name_attribute => true
 +attribute :port, :kind_of => [Integer, String], :name_attribute => true, :regex => /\d+/
```
I don't have the time for testing it.
Also don't worry about version numbers, I have a system for it :)

**Comment by equick** [comment]
Clever, I forgot Chef could do that :) I tested it with some different values:

1234     - passed
"1234"  - passed
"12ef" - chef run fails with: 
`STDERR: ValueError: invalid literal for int() with base 10: '12ff'
FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)`
"ffff" - execute skipped due to not_if..... The chef client run ends with this message: 
`Default value "ffff" is invalid for property port of resource selinux_policy_port. In Chef 13 this will become an error: Option port's value ffff does not match regular expression /\d+/. at 1 location
`

**Comment by BackSlasher** [comment]
so the validation doesn't work with `name_attribute`. Bummer. Let's try
thinking about something else

*Nitzan Raz*
http://backslasher.net

**Comment by equick** [comment]
I asked about this in the Chef IRC channel and @coderanger gave me some help:
```
<quick> ...so just to confirm my understanding, that means the attribute line I originally wrote should cause a hard error from Chef 13 if the user passes a string instead of an integer
<coderanger> That is correct.
<coderanger> Because we don't want to break backwards compat, we can't currently "really" validate things coming in via name_attribute.
```

**Comment by shortdudey123** [comment]
@equick this appears to have been fixed in master via your commits https://github.com/BackSlasher/chef-selinuxpolicy/commit/387225487e4a77568c70e005a4154068153f20c3

**Comment by BackSlasher** [comment]
I believe. Please reopen if not
