### ISSUE TITLE
Packages required for selinux_policy_module

### ISSUE THREAD

**Issue by jhmartin** [BackSlasher/chef-selinuxpolicy#46]
On RHEL/CentOS, `package 'selinux-policy-devel'` is required to add new policy modules.

**Comment by BackSlasher** [comment]
Hi.
Can I get a little more detail, like specific OS, error?

Thanks

*Nitzan Raz*
http://backslasher.net

**Comment by jhmartin** [comment]
https://forums.fogproject.org/topic/6154/selinux-policy demonstrates the issue:
```
make: /usr/share/selinux/devel/Makefile: No such file or directory
make: *** No rule to make target `/usr/share/selinux/devel/Makefile'.  Stop.
```

**Comment by BackSlasher** [comment]
I think I have a test for that in the kitchen (runnable via `kitchen test`).
I'm not in position for testing - could you please check it?
If not I'll do it some other time

**Comment by jhmartin** [comment]
The test passes as your 7.2 box comes with that packages preinstalled, but it is not part of the vanilla installation.

**Comment by BackSlasher** [comment]
https://github.com/BackSlasher/chef-selinuxpolicy/blob/f52ee57/recipes/install.rb#L22
Did you include `selinux_policy::install` in your run?

**Comment by jhmartin** [comment]
I am apparently blind.

**Comment by BackSlasher** [comment]
Thanks for using and reporting, GL etc
If we need to stress it more in the README I'll accept PRs! :)

*Nitzan Raz*
http://backslasher.net
