### ISSUE TITLE
Current version doesn't allow to adapt symlink labels

### ISSUE THREAD

**Issue by daften** [BackSlasher/chef-selinuxpolicy#51]
For that -f -l (of -f l for RHEL>7) is needed.

**Comment by BackSlasher** [comment]
Hey @daften 
Thanks for letting me know. Would you like to suggest a PR for that?

**Comment by daften** [comment]
Jup, I will try to create one over the course of the next week. :)
Thanks for the quick reply!

**Comment by daften** [comment]
Added a PR: #52 
Still working on it, but feel free to comment

**Comment by daften** [comment]
The PR is finished as far as I'm concerned, feedback welcome.

I also noticed that one of the tests through kitchen fails, since the relabel's aren't always done immediately. I've re-enabled the faulty test in my last commit, couldn't figure out why it was failing exactly, or how to fix it, besides doing an extra relabel just before, or setting the relabel notification on the modify action to :immediately.

**Comment by BackSlasher** [comment]
Thanks for the contribution. Let's continue further discussion in the PR.
CC @equick if you wanna take a peek

**Comment by BackSlasher** [comment]
fixed by 394cd97c08bb27067db9085a63ccd950121c4184
