### ISSUE TITLE
ERROR: incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by alexb-uk** [BackSlasher/chef-selinuxpolicy#6]
Hi,

I was going to give your cookbook a try as it looked like just the thing I need however I'm struggling to get past the first step.

Chef server web ui displays the message "ERROR: incompatible character encodings: UTF-8 and ASCII-8BIT" when I attempt to view 0.6.1 or 0.6.0.

I don't know if its related but my recipe then fails to compile on chef-client run:

``` ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/vszendserver/recipes/default.rb
  ================================================================================

  NoMethodError
  -------------
  No resource or method named `selinux_policy_boolean' for `Chef::Recipe "default"'

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/vszendserver/recipes/default.rb:149:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/vszendserver/recipes/default.rb:

  146:  #######################
  147:  # Set SELinux config
  148:  #######################
  149>> selinux_policy_boolean 'httpd_can_network_connect_db' do
  150:      value true
  151:  end
  152:
  153:  selinux_policy_boolean 'httpd_can_network_memcache' do
  154:      value true
  155:  end
  156:
  157:  selinux_policy_port '10083' do
  158:      protocol 'tcp'
```

I've tried various combinations of version constraints in my metadata.rb but none seem to make a difference and the dependency on selinux_policy never seems to get pulled in.

Thanks for your help

Alex

**Comment by BackSlasher** [comment]
I see we have some incompatible encoding. Serves me right for accepting PRs :)
Do you use Chef 12 by any chance? It's [supposed to be fixed there](https://github.com/opscode-cookbooks/chef-client/issues/213)
I'll fix it anyway

**Comment by BackSlasher** [comment]
Well [Jörg Herzinger](https://github.com/joerg) is to blame since he has `ö`. I'll try rencoding everything in UTF8

**Comment by alexb-uk** [comment]
Thanks for the quick response.

We're actually using a mixture of versions at the moment, chef-server 11.1.5 but I was testing using the latest Chef client, v12.1.2.

Cheers

Alex

**Comment by BackSlasher** [comment]
I think the Chef Server fudges it up.
Please try adding `# encoding: utf-8` to the files `./README.md` and
`./libraries/helper-restorecon.rb`
If that fails, try adding the header to everything else.
LMK if this helps. I just don't have a Chef 11 environment to work with.

*Nitzan Raz*
http://backslasher.net

**Comment by alexb-uk** [comment]
Tried adding the encoding to those two files but no joy unfortunately.

We do have a plan to upgrade the Chef server to v12 so I'll probably concentrate on doing that instead.

Cheers

Alex

**Comment by BackSlasher** [comment]
Should be solved anyway. Decided to demote `Jörg` to `Joerg`

**Comment by alexb-uk** [comment]
Great stuff thanks.

Will give this another try in my next bit of down time.

**Comment by alexb-uk** [comment]
Just wanted to let you know that your change did indeed fix both issues.

No longer seeing an error on the Chef Server web UI and the resource is firing as expected during chef-client runs.

Thanks again.

Alex

**Comment by BackSlasher** [comment]
NP. May you upgrade soon :)
