### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by shortdudey123** [BackSlasher/chef-selinuxpolicy#61]
Hi!  I am part of the sous-chefs community org.  We saw your request for a new maintainer of this cookbook and would like to take you up on the offer.

https://github.com/sous-chefs
https://supermarket.chef.io/users/sous-chefs

Let me know if that would me possible :)

**Comment by BackSlasher** [comment]
Hi, thanks for writing!
I'd be happy to get some help with handling things around here. Please ping me at nitz.raz@gmail.com and we can get talking.

**Comment by shortdudey123** [comment]
Emailed
